dados_governo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: RZFQSVC-JX11949
      user: MARCIOMICHELOTTO
      authenticator: snowflake
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: GOV_V3
      warehouse: COMPUTE_WH
      schema: DADOS_GOV
      threads: 4
