CREATE OR REPLACE TASK TASK_CARREGA_BRONZE
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 2 * * * America/Sao_Paulo'
AS
    COPY INTO TB_BRONZE_DESPESAS_V2
    FROM '@AWS_STAGE/despesasPorOrgao(in).csv'
    FILE_FORMAT = CSV_TAB_FORMAT
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK TASK_BRONZE_TO_SILVER
    WAREHOUSE = COMPUTE_WH
    AFTER TASK_CARREGA_BRONZE
AS
    CALL SP_BRONZE_TO_SILVER();

CREATE OR REPLACE TASK TASK_SILVER_TO_GOLD
    WAREHOUSE = COMPUTE_WH
    AFTER TASK_BRONZE_TO_SILVER
AS
    CALL SP_SILVER_TO_GOLD();

ALTER TASK TASK_CARREGA_BRONZE RESUME;
ALTER TASK TASK_BRONZE_TO_SILVER RESUME;
ALTER TASK TASK_SILVER_TO_GOLD RESUME;
