LIST @AWS_STAGE;

CREATE OR REPLACE FILE FORMAT CSV_TAB_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = '\t'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', '')
    EMPTY_FIELD_AS_NULL = TRUE
    ENCODING = 'ISO88591';
